name: Sorting Plugin
main: me.jesfot.sortplug.bukkit.BukkitPlugin
version: 2.5.0-ALPHA
description: Simple plugin that sort items passed in a hopper. #Configuring filter not terminated
authors: ["JesFot"] #Can I add an helper ? ;)
permissions: #Not implemented yet
  sortp.*:
    description: All plugin commands and access
    children:
      sortp.setitems: true
      sortp.owner: true
  sortp.setitems:
    description: Set item filter
    default: true
  sortp.owner:
    description: Define the owner and persons can configure the filter
    default: true
commands:
  testspplugin:
    description: This command test if the plugin is active
    usage: /<command>
  addfilter:
    description: Nop.
    usage: /<command> [x, y, z] <itemType>